defmodule Waxx.Kanban.BoardLabelSubboard do
  @moduledoc """
  Join row scoping a `BoardLabel` to a `Subboard`. A label with no rows here
  is board-wide; rows restrict it to the listed subboards. Used as the
  `join_through` schema for `BoardLabel.subboards` so the join's UUID primary
  key and timestamps are autogenerated like every other table.
  """
  use Waxx.Schema

  alias Waxx.Kanban.{BoardLabel, Subboard}

  schema "board_label_subboards" do
    belongs_to :board_label, BoardLabel
    belongs_to :subboard, Subboard

    timestamps(type: :utc_datetime)
  end
end
