defmodule WaxxWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :waxx

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_waxx_key",
    signing_salt: "Rl43SDOI",
    same_site: "Lax"
  ]

  # :uri and :x_headers are exposed so LiveViews can derive the public-facing
  # base URL (see WaxxWeb.PublicUrl) for things like the API-token pairing QR.
  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [:uri, :x_headers, session: @session_options]],
    longpoll: [connect_info: [:uri, :x_headers, session: @session_options]]

  # Native-client channels socket. Authenticated by api-context bearer
  # passed as `?token=...` at connect time; see WaxxWeb.UserSocket.
  socket "/socket", WaxxWeb.UserSocket,
    websocket: true,
    longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :waxx,
    gzip: not code_reloading?,
    only: WaxxWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :waxx
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug WaxxWeb.Router
end
