import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :waxx, WaxxWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# SSL is terminated at the Traefik edge (see app.yml — the
# `redirect-https` middleware bounces http→https there). Phoenix never
# sees TLS directly: requests arrive on the pod as plaintext with
# `X-Forwarded-Proto: https`. We deliberately do NOT install
# `force_ssl` here — when it ran, any request whose X-Forwarded-Proto
# header didn't make it through ended up 301'd to https by Phoenix,
# which then broke WebSocket upgrades (the channels client can't
# follow redirects on /socket/websocket).
#
# To re-enable HSTS without the redirect, add `:put_secure_browser_headers`
# adjustments to the router pipeline instead.

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
